### ISSUE TITLE
Resumen del apartado Manifiesto Ágil

### ISSUE THREAD

**Issue by VictoriaGarciaLovelle** [UrkoAlliBarrena/Realizar-una-Wiki-utilizando-gesti-n-de-tareas#3]
Scrum valora individuos, software funcional, colaboración y adaptabilidad al cambio. 

1. Valoramos más a los individuos y su interacción que a los procesos y las herramientas: Scrum valora creatividad e innovación por encima de procesos inflexibles.
2.  Valoramos más el software que funciona, por encima de la documentación exhaustiva: Scrum valora documentación relevante, pero no más que el producto.
3.  Valoramos más la colaboración con el cliente que la negociación contractual: el objetivo de proyecto ágil es el valor continuo, feedback directo y colaboración cliente-equipo.
4. Valoramos más la respuesta al cambio que el seguimiento de un plan: Scrum valora anticipación y adaptación sobre planificación y control ortodoxos.

**Principios del Manifiesto Ágil**
El Manifiesto Ágil establece 12 principios, incluyendo la entrega temprana y continua de software de valor al cliente, la flexibilidad para requisitos cambiantes, la colaboración entre negocios y desarrolladores, la comunicación cara a cara, la atención a la excelencia técnica y la reflexión constante para mejorar la efectividad del equipo.

**Origen del Scrum**
Scrum es un modelo ágil de desarrollo basado en equipos autónomos, estrategia incremental y solapamiento de fases, surgido en Japón en los 80.

**Comment by UrkoAlliBarrena** [comment]
«Valoramos más a los individuos y su interacción que a los procesos y las herramientas.»
![image](https://user-images.githubusercontent.com/126605718/230983411-901e8fcf-56ed-4c1f-8b2a-c8c37145d2ad.png)

**Comment by UrkoAlliBarrena** [comment]
«Valoramos más el software que funciona, por encima de la documentación exhaustiva.»
![image](https://user-images.githubusercontent.com/126605718/230983448-fd21add4-3536-441d-b314-0157b570a113.png)

**Comment by UrkoAlliBarrena** [comment]
«Valoramos más la colaboración con el cliente que la negociación contractual.»
![image](https://user-images.githubusercontent.com/126605718/230983510-4b0f1ac2-5114-46b8-be97-bc3462d3c556.png)

**Comment by UrkoAlliBarrena** [comment]
«Valoramos más la respuesta al cambio que el seguimiento de un plan.»
![image](https://user-images.githubusercontent.com/126605718/230983556-50e39c58-02f7-441f-8d93-cb7cfdbb8d1c.png)
